name: Publish to Dockerhub
on: [push]
  # push:
  #   branches:
  #     - master
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Dockerhub
        uses: docker/build-push-action@v1
        with:
          repository: razorpay/querybook
          username: ${{ secrets.PUBLIC_DOCKERHUB_USERNAME }}
          password: ${{ secrets.PUBLIC_DOCKERHUB_PASSWORD }}
          tags: latest
